### ISSUE TITLE
Error con Angular al intentar instalar en Huayra 3.3.

### ISSUE THREAD

**Issue by malefico3d** [HuayraLinux/huayra-compartirweb#8]
Intentando instalar rama "estable" en Huayra 3.3 (maquina virtual). 
Actualizo repo. Cambio a rama "estable".
Edito package.json, modifico linea por "git+https://github.com/iglosiggio/nwjs-hack.git"
Hago `npm install` tira error relativo a bower.
Hago `npm install bower`
Hago `node_modules/.bin/bower install`
Hago `npm install`
Termina sin errores.
Hago `nw ./src`
Me da estos errores relativos a angular:

```console
alumno@huayra:~/Documentos/huayra-compartirweb$ nw src/
[11159:0523/115434:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
OpenGL Warning: glXChooseFBConfig returning NULL, due to attrib=0x2, next=0x20
[11176:0523/115434:ERROR:gl_surface_glx.cc(637)] glXChooseFBConfig failed.
[11176:0523/115434:ERROR:gpu_info_collector.cc(27)] gfx::GLContext::CreateOffscreenGLSurface failed
[11176:0523/115434:ERROR:gpu_info_collector.cc(89)] Could not create surface for info collection.
[11176:0523/115434:ERROR:gpu_main.cc(410)] gpu::CollectGraphicsInfo failed (fatal).
[11176:0523/115434:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[11176:0523/115434:ERROR:gpu_child_thread.cc(146)] Exiting GPU process due to errors during initialization
[11159:0523/115435:ERROR:nw_shell.cc(336)] ReferenceError: angular is not defined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/app.js:27:11
[11159:0523/115435:INFO:CONSOLE(27)] "Uncaught ReferenceError: angular is not defined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/app.js (27)
[11159:0523/115435:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'factory' of undefined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/singleton.js:1:4
[11159:0523/115435:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'factory' of undefined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/singleton.js (1)
[11159:0523/115435:ERROR:nw_shell.cc(336)] ReferenceError: angular is not defined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/versionFactory.js:1:11
[11159:0523/115435:INFO:CONSOLE(1)] "Uncaught ReferenceError: angular is not defined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/versionFactory.js (1)
[11159:0523/115435:ERROR:nw_shell.cc(336)] ReferenceError: angular is not defined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/amigosFactory.js:1:11
[11159:0523/115435:INFO:CONSOLE(1)] "Uncaught ReferenceError: angular is not defined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/amigosFactory.js (1)
[11159:0523/115435:ERROR:nw_shell.cc(336)] ReferenceError: angular is not defined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/avahiFactory.js:1:11
[11159:0523/115435:INFO:CONSOLE(1)] "Uncaught ReferenceError: angular is not defined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/avahiFactory.js (1)
[11159:0523/115435:ERROR:nw_shell.cc(336)] ReferenceError: angular is not defined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/preferenciasFactory.js:1:11
[11159:0523/115435:INFO:CONSOLE(1)] "Uncaught ReferenceError: angular is not defined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/preferenciasFactory.js (1)
[11159:0523/115435:ERROR:nw_shell.cc(336)] ReferenceError: angular is not defined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/redFactory.js:1:11
[11159:0523/115435:INFO:CONSOLE(1)] "Uncaught ReferenceError: angular is not defined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/redFactory.js (1)
[11159:0523/115435:ERROR:nw_shell.cc(336)] ReferenceError: angular is not defined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/controllers/amigosCtrl.js:1:11
[11159:0523/115435:INFO:CONSOLE(1)] "Uncaught ReferenceError: angular is not defined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/controllers/amigosCtrl.js (1)
[11159:0523/115435:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'controller' of undefined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/controllers/archivosCtrl.js:6:4
[11159:0523/115435:INFO:CONSOLE(6)] "Uncaught TypeError: Cannot read property 'controller' of undefined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/controllers/archivosCtrl.js (6)
[11159:0523/115435:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'controller' of undefined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/controllers/preferenciasCtrl.js:8:4
[11159:0523/115435:INFO:CONSOLE(8)] "Uncaught TypeError: Cannot read property 'controller' of undefined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/controllers/preferenciasCtrl.js (8)
[11159:0523/115435:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'controller' of undefined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/controllers/notificacionesCtrl.js:1:4
[11159:0523/115435:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'controller' of undefined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/controllers/notificacionesCtrl.js (1)
[11159:0523/115435:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'controller' of undefined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/controllers/descargasCtrl.js:3:4
[11159:0523/115435:INFO:CONSOLE(3)] "Uncaught TypeError: Cannot read property 'controller' of undefined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/controllers/descargasCtrl.js (3)
[11159:0523/115435:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'directive' of undefined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/directives/directives.js:1:4
[11159:0523/115435:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'directive' of undefined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/directives/directives.js (1)
[11159:0523/115436:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'factory' of undefined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/factories.js:17:4
[11159:0523/115436:INFO:CONSOLE(17)] "Uncaught TypeError: Cannot read property 'factory' of undefined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/factories/factories.js (17)
[11159:0523/115436:ERROR:nw_shell.cc(336)] ReferenceError: angular is not defined
    at file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/filters/filters.js:1:7
[11159:0523/115436:INFO:CONSOLE(1)] "Uncaught ReferenceError: angular is not defined", source: file:///home/alumno/Documentos/huayra-compartirweb/src/assets/js/filters/filters.js (1)
```

**Comment by iglosiggio** [comment]
Creo que tengo una idea de por dónde puede venir esto, mañana lo reviso y
reparo todo lo que encuentre en el branch estable

**Comment by iglosiggio** [comment]
Bueno, dejo el paso a paso acá y después lo paso al readme de la branch:

1. `git clone https://github.com/HuayraLinux/huayra-compartirweb`
2. `cd huayra-compartirweb`
3. `git checkout estable`
4. `npm install`
5. `cd src`
6. `../node_modules/.bin/bower install`
7. `nw .`
8. ???
9. Profit!
